<?php

return [
    'database' => [
        'dataType' => [
            // 'bigInteger',
            // 'binary',
            // 'boolean',
            // 'char',
            // 'date',
            // 'dateTime',
            // 'dateTimeTz',
            // 'decimal',
            // 'double',
            // 'enum',
            // 'float',
            // 'integer',
            // 'ipAddress',
            // 'json',
            // 'jsonb',
            // 'longText',
            // 'macAddress',
            // 'mediumInteger',
            // 'mediumText',
            // 'morphs',
            // 'nullableMorphs',
            // 'nullableTimestamps',
            // 'rememberToken',
            // 'smallInteger',
            // 'softDeletes',
            // 'string',
            // 'text',
            // 'time',
            // 'timeTz',
            // 'tinyInteger',
            // 'timestamp',
            // 'timestampTz',
            // 'timestampsTz',
            // 'unsignedBigInteger',
            // 'unsignedInteger',
            // 'unsignedMediumInteger',
            // 'unsignedSmallInteger',
            // 'unsignedTinyInteger',
            // 'uuid',
            'string' => 'VARCHAR',
            'json' => 'JSON',
            'integer' => 'INT',
            'unsignedInteger' => 'UNSIGNED INT',
            'tinyInteger' => 'TINYINT',
            'unsignedTinyInteger' => 'UNSIGNED TINYINT',
            'float' => 'FLOAT',
            'text' => 'TEXT',
            'double' => 'DOUBLE',
            'timestamp' => 'TIMESTAMP',
            'boolean' => 'BOOLEAN',
            'date' => 'DATE',
            'dateTime' => 'DATETIME',
        ],
        'numb' => [
            'integer',
            'unsignedInteger',
            'tinyInteger',
            'unsignedTinyInteger',
            'float',
            'double'
        ],
        'text' => [
            'string',
            'json',
            'text',
        ],
        'formElement' => [
            'text',
            'password',
            'email',
            'textarea',
            'textarea with CKEditor',
            'number',
            'checkbox',
            'radio',
            'datetimepicker',
            'datepicker',
            'file upload single',
            'file upload multiple',
            'select',
        ]
    ],
    'image' => [
        'thumb' => [
            'width' => 100,
            'height' => 100
        ]
    ]
];